### ISSUE TITLE
[Windows] HostProcess base image

### ISSUE THREAD

**Issue by marosset** [Azure/container-upstream#120]
Create a new base image for HostProcess containers

**Comment by marosset** [comment]
https://github.com/microsoft/windows-host-process-containers-base-image/pull/1

**Comment by marosset** [comment]
https://github.com/microsoft/mcr/pull/2122

**Comment by dtzar** [comment]
@marosset Those issues appear to be closed, so this is complete, no?

**Comment by marosset** [comment]
Yes this is done!
