### ISSUE TITLE
AKS Engine VHD Updates

### ISSUE THREAD

**Issue by jackfrancis** [Azure/container-upstream#128]
Ubuntu 20.04-LTS VHD shipped here: https://github.com/Azure/aks-engine/pull/5041

**Comment by jackfrancis** [comment]
Nov release: https://github.com/Azure/aks-engine/releases/tag/v0.73.0
Dec release: https://github.com/Azure/aks-engine/releases/tag/v0.74.0
Jan release: https://github.com/Azure/aks-engine/releases/tag/v0.75.0
Feb release: https://github.com/Azure/aks-engine/releases/tag/v0.76.0
March release: TODO
April release: TODO

I believe we can close this issue after we fulfill the April release commitment. Does that sound right @bridgetkromhout @dtzar @CecileRobertMichon ?

**Comment by dtzar** [comment]
Complete now with April release: https://github.com/Azure/aks-engine/releases/tag/v0.78.0
