### ISSUE TITLE
Track work needed to migrate upstream Windows tests from aks-engine to CAPZ

### ISSUE THREAD

**Issue by marosset** [Azure/container-upstream#98]
## Blocking 
- [x] Taint master / linux nodes when running upstream e2etest
- [x] Get GMSA tests running with CAPZ clusters
  - [x] Add post kubeadm task to configure GMSA? 
- [x] k/k PR job support 
  - [x] Use Windows node binaries built from PR branch
  - [x] Use control plane components (kube-apiserver, scheduler etc, built from PR branch)
- [x] Determine where to host cluster configs (kubernetes-sigs/windows-testing?)
- [x] Decide if we want to regularly publish VHDs to help cluster provisioning times
  - [x] Stick with current cadence (every K8s patch release) 
- [x] containerd support in capz
  - [x] ~Post kubeadm action to configure CNI on the node~ used hostprocess containers 
- [x] Decide which CNIs / configurations we should use for upstream test (Calico to gain DSR and network policy support??)
- [x] Ensure log collection scripts work with CAPZ/Windows nodes during upstream tests
- [x] csi proxy tests
- [x] move release jobs to capz

## Non-Blocking
- [x] Windows billing extension for CAPZ
- [x] Transfer ownership of signed provisioning scripts to AKS team

**Comment by marosset** [comment]
@jsturtevant

**Comment by jsturtevant** [comment]
Related: https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/1119

**Comment by CecileRobertMichon** [comment]
@jsturtevant @marosset what's the status on gmsa tests? can this be closed?

**Comment by jsturtevant** [comment]
They are ready to merge here: https://github.com/kubernetes-sigs/windows-testing/pull/328

**Comment by jsturtevant** [comment]
we are fully moved off aks-engine to capz at this point 🤖
